### ISSUE TITLE
CouchDB - Query Selector IN List Issues with AccountRepo

### ISSUE THREAD

**Issue by rtclauss** [eclipse/jnosql-communication-driver#185]
I'm using a repository with CouchDB and would like to select all the documents which match one of the owners in a list. This is my query in my repo interface:
```java
public interface AccountRepository extends Repository<Account, String> {
...
  @Query("select * from Account where owner in (@owners)")
  List<Account> findByOwnerIn(@Param("owners") List<String>owners);
...
}
```

If I pass in a `List<String>` of owners the MangoQuery that is generated contains a double-nested array like so:
```json
{"selector":{"@entity":"Account","owner":{"$in":[["Ryan"]]}}}
```

Here's a screen cap of this in the debugger:
![image](https://user-images.githubusercontent.com/1046259/197088628-e0979421-1e18-4180-98e3-3eca81a8ee55.png)

This causes a 500 error when the query runs against the database. Here is the stack trace.
[stacktrace.txt](https://github.com/eclipse/jnosql-communication-driver/files/9835442/stacktrace.txt)

I can also verify this in Fauxton by replacing the sample query
![image](https://user-images.githubusercontent.com/1046259/197089348-2ec2af59-ecd3-448e-91ff-9c4fed101163.png)

When I remove the extra array elements I get the proper results:
![image](https://user-images.githubusercontent.com/1046259/197089282-31c4e269-fe76-487f-bddc-260508ad5459.png)

This happens regardless of the length of the list. Here, I've used a simplified case with a single list value. Had there been two values in the `List` the generated MangoQuery becomes:
```json
{"selector":{"@entity":"Account","owner":{"$in":[["Ryan", "9sOfVRacTRDuWeoTPHRk"]]}}}
```

If I replace the java code with this:
```java
List<Account> findByOwnerIn(List<String> owners);
```

The generated MangoQuery becomes:
```json
{"selector": {"@entity": "Account","owner": {"$in": ["[Ryan]"]}}}
```
which again contains a double-nested array but this time the inner array has now been cast as a string. The query runs but 0 results are returned.

Running this query in Fauxton does work but there is no document with the `owner` value of `[Ryan]`
![image](https://user-images.githubusercontent.com/1046259/197095075-5877bfc0-1b9f-4849-8685-d47f0deb6efb.png)

This happens regardless of the length of the list. Here, I've used a simplified case with a single list value. Had there been two values in the `List` the generated MangoQuery becomes:
```json
{"selector":{"@entity":"Account","owner":{"$in":["[Ryan, 9sOfVRacTRDuWeoTPHRk]"]}}}
```

**Comment by otaviojava** [comment]
Thank you for the feedback, I'll take a look this morning.
